version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: lfgm
      MYSQL_USER: lfgm
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306"
    expose:
      - "3306"
  app:
    build:
      context: .
    ports:
      - "9001:9001"
    depends_on:
      - db