version: "2"
services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    image: mysql:5.7
    ports:
      - "3306:3306"
    expose:
      - "3306"
  app:
    build:
      args:
        PORT: ${PORT}
      context: .
    container_name: lfgm-container
    ports:
      - "9001:9001"
    depends_on:
      - db